### ISSUE TITLE
Cannot plot curves-AttributeError: 'NoneType' object has no attribute 'isCosmetic'

### ISSUE THREAD

**Issue by yuanyuanhe2021** [CellMechLab/nanoindentation#6]
Hi,

I had problem in using nanoindentation-1.0.0, could you please help me solve it? 

I've successfully used NanoPrepare-0.1.1 to prepare JSON file, but when running nano.py of nanoindentation-1.0.0,  it errors once I load the json file( and cannot plot any curve)  :

Traceback (most recent call last):
  File "/Users/heyuanyuan/Desktop/nanoindentation-1.0.0/nano.py", line 345, in loadExperiment
    self.ui.g_fdistance.plotItem.addItem(self.fdistance_fit)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyqtgraph/graphicsItems/PlotItem/PlotItem.py", line 535, in addItem
    self.vb.addItem(item, *args, **vbargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyqtgraph/graphicsItems/ViewBox/ViewBox.py", line 417, in addItem
    self.updateAutoRange()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyqtgraph/graphicsItems/ViewBox/ViewBox.py", line 930, in updateAutoRange
    childRange = self.childrenBounds(frac=fractionVisible)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyqtgraph/graphicsItems/ViewBox/ViewBox.py", line 1430, in childrenBounds
    pxPad = 0 if not hasattr(item, 'pixelPadding') else item.pixelPadding()
  **File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-**packages/pyqtgraph/graphicsItems/PlotCurveItem.py", line 289, in pixelPadding
    if pen.isCosmetic():
AttributeError: 'NoneType' object has no attribute 'isCosmetic'**

It seems like that the json file is not successfully loaded.

I was wondering what I could do to solve it?

Thank you very much!

**Comment by massimovassalli** [comment]
Hi! Can you upload the json file? From the error, it looks like there is at least one curve which is empty ...
